# Generated by Django 5.0.3 on 2024-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donationarea_donation_gallery_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donationpc',
            new_name='donationpic',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Footwear Donation', 'Footwear Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Food Donation'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
